### ISSUE TITLE
Lessons tables and add unit display

### ISSUE THREAD

**Issue by isabelleyzhou** [codebase-berkeley/teacher-portal#64]
create the table for the lessons page and add a unit display feature

**Comment by bchee** [comment]
@isabelleyzhou please add this to the project and label it

**Comment by kelvinjue** [comment]
add it to the project?

**Comment by bchee** [comment]
The project board it's on the right column. Do this for all issues.

**Comment by isabelleyzhou** [comment]
what type of label?

**Comment by bchee** [comment]
Most are enhancement or new feature
